# Generated by Django 6.0.6 on 2026-07-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_deleted_task_deleted_at'),
        ('todo', '0004_alter_task_id'),
    ]

    operations = [
    ]
